# Generated by Django 5.2 on 2025-05-05 11:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='batch_frequency',
            field=models.CharField(choices=[('daily', '毎日'), ('weekly', '毎週'), ('monthly', '毎月'), ('none', 'なし')], default='daily', max_length=10, verbose_name='バッチ処理頻度'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='default_view',
            field=models.CharField(choices=[('list', 'リスト表示'), ('grid', 'グリッド表示')], default='list', max_length=20, verbose_name='デフォルト表示形式'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='email_notifications',
            field=models.BooleanField(default=True, verbose_name='メール通知'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='max_cross_search_docs',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1)], verbose_name='横断検索最大文書数'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='max_file_size_mb',
            field=models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(1)], verbose_name='最大ファイルサイズ(MB)'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='max_pages',
            field=models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(1)], verbose_name='最大ページ数'),
        ),
    ]
